version: "3.8"

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    depends_on:
      - elasticsearch

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_FIREBASE_KEY = ${VITE_FIREBASE_KEY}
      - VITE_FIREBASE_DOMAIN=${VITE_FIREBASE_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID = ${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET =${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_SENDER_ID =  ${VITE_FIREBASE_SENDER_ID}
      - VITE_FIREBASE_APP_ID = ${VITE_FIREBASE_APP_ID}
    depends_on:
      - backend

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
