version: "3.8"

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://achaurasia:6W1Fd0svpG5lLoby@dev-opuslink-internal.p39zf.mongodb.net/?retryWrites=true&w=majority&appName=dev-opuslink-internal
      - DB_NAME=OpusLink
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_FIREBASE_KEY = AIzaSyCukZtpxtR9e7bNYvxh6ogTO6TgdMg7cyY
      - VITE_FIREBASE_DOMAIN= opuslink.firebaseapp.com
      - VITE_FIREBASE_PROJECT_ID = opuslink 
      - VITE_FIREBASE_STORAGE_BUCKET =opuslink.firebasestorage.app
      - VITE_FIREBASE_SENDER_ID =  696724111445
      - VITE_FIREBASE_APP_ID = 1:696724111445:web:14b72fa6402176857794dc
    depends_on:
      - backend

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
